# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Envio-Indexer
networks:
- id: 84532
  start_block: 0
  contracts:
  - name: VaultFactory
    address:
    - 0x56ab9F1E53D3696766EE2eb13af8D4540924b4B0
    handler: src/EventHandlers.ts
    events:
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: VaultCreated(address indexed user, address indexed vault, uint256 timestamp)
    - event: VaultRemoved(address indexed user, address indexed vault)
  - name: UserVault
    handler: src/EventHandlers.ts
    events:
    - event: AutoSyncTriggered(address indexed token, uint256 timestamp)
    - event: BalanceSynced(address indexed token, uint256 oldBalance, uint256 newBalance, uint256 timestamp)
    - event: OwnershipTransferred(address indexed previousOwner, address indexed newOwner)
    - event: TokenAdded(address indexed token, uint256 timestamp)
    - event: TokenRemoved(address indexed token, uint256 timestamp)
    - event: TokensReceived(address indexed token, uint256 amount, address indexed from, uint256 timestamp)
    - event: TokensWithdrawn(address indexed token, uint256 amount, address indexed to, uint256 timestamp)
unordered_multichain_mode: true
preload_handlers: true
